### ISSUE TITLE
Adding the new set of N0va wallpapers/Screen tearing issue

### ISSUE THREAD

**Issue by Kusanalee** [yoshidan/N0vaMac#1]
Is it possible to add the newer set of N0va Desktop wallpapers or are the wallpapers in the app the only given ones? - It would be cool too if the user could also add wallpapers alongside the preloaded ones. I've tried messing around in Unity a bit trying to implement new ones (and failing miserably). Also, I encounter an issue on Sonoma where the windows has screen tears when n0vamac is open.

**Comment by yoshidan** [comment]
You can use the .ndf file of the `N0va Desktop` directly. The following steps should work.
(.ndf file is the just mp4 that contains 2 byte dummy data) .

1. Download `.ndf` file from `N0va Desktop` on Windows.
2. Cut first 2 bytes from `.ndf` and save on any location (ex `$HOME/.local/share/test.mp4`)
3. Write movie path into `path.txt` which is read by `N0VaMac`
    ```
    echo $HOME/.local/share/test.mp4 > $HOME/Library/Application Support/com.com.github.yoshidan.N0vaMac/path.txt
   ```

**Comment by Kusanalee** [comment]
Thank you! I'll try it - and apparently in my testing the screen tearing issues only happen when on battery power so it's probably some weird Apple efficiency battery thing.
